name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Admin@123
          MYSQL_DATABASE: CustomerDemoDb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
        coverage: xdebug

    - uses: actions/checkout@v3

    - name: Copy .env
      run: cp .env.docker .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Install Passport
      run: php artisan passport:install

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit

  docker:
    needs: laravel-tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false  # Set to true if you want to push to a registry
        tags: blog-api:latest
        # Uncomment below lines to push to Docker Hub or another registry
        # username: ${{ secrets.DOCKER_USERNAME }}
        # password: ${{ secrets.DOCKER_PASSWORD }}

    # Deployment step (commented out as requested)
    # - name: Deploy to production
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # Add deployment commands here
    #     # For example: ssh into server, pull new image, restart containers
